name: Auto PR Creation

on:
  push:
    branches:
      - develop
      - 'feature/*'
      - 'fix/*'

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Auto PR from ${{ github.ref_name }}
        title: '[Auto PR] Changes from ${{ github.ref_name }}'
        body: |
          ## Automated Pull Request
          
          This PR was automatically created from branch `${{ github.ref_name }}`.
          
          ### Changes
          - Review the changes in the Files tab
          - Preview deployment will be created automatically
          
          ### Checklist
          - [ ] HTML validation passed
          - [ ] Lighthouse tests passed
          - [ ] Preview deployment looks good
          
        branch: auto-pr/${{ github.ref_name }}
        base: main
        labels: |
          automated
          needs-review