name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Quick HTML Check
      run: |
        # Basic HTML validation - just check for major issues
        if ! grep -q "</html>" index.html; then
          echo "HTML file seems incomplete"
          exit 1
        fi
        echo "✓ HTML structure looks good"
    
    - name: Deploy to Vercel
      env:
        VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      run: |
        npx vercel --prod --token=$VERCEL_TOKEN --scope=${{ secrets.VERCEL_SCOPE }} --yes
        echo "✓ Deployed to production"